repos:
  # default hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  # Ruff
  - repo: local
    hooks:
    - id: ruff-CLI
      name: ruff-CLI
      entry: bash -c "ruff check * --select E,W,F,S --extend-select C4,SIM,RET,PT,I001,ANN001,ANN201,ANN205,ANN206,ARG001 --ignore E501,E731,S108,S101,S113,S603,PT007,S310,E402,PT004,C408 --per-file-ignores "*/**/__init__.py":I001,"*/**/__init__.py":F401,"tests/*":ANN,"*/**/unsloth/kernels/*":ALL --line-length 120 --target-version py38 --fix-only"
      language: system
      pass_filenames: false

  # Black
  - repo: local
    hooks:
    - id: black-CLI
      name: black-CLI
      entry: bash -c "black -l120 -C --preview --target-version py38 config_hub eval extensions litgpt tests --exclude unsloth/kernels"
      language: system
      pass_filenames: false

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint-fix
        args:
          - --disable
          - MD013 # line-length
          - MD033 # no-inline-html
